package uk.co.somestuff.dave.walldisplaycontroller._22_01_2022;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2022-01-23T16:02:28.675Z
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", name = "WallDisplayController1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface WallDisplayController1Soap {

    @WebMethod(operationName = "GetConfiguration", action = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022/GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", className = "uk.co.somestuff.dave.walldisplaycontroller._22_01_2022.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", className = "uk.co.somestuff.dave.walldisplaycontroller._22_01_2022.GetConfigurationResponse")
    @WebResult(name = "GetConfigurationResult", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022")
    public uk.co.somestuff.dave.walldisplaycontroller._22_01_2022.Configuration getConfiguration(

        @WebParam(name = "TokenHeader", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", header = true)
        TokenHeader tokenHeader
    );

    @WebMethod(operationName = "GetMessages", action = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022/GetMessages")
    @RequestWrapper(localName = "GetMessages", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", className = "uk.co.somestuff.dave.walldisplaycontroller._22_01_2022.GetMessages")
    @ResponseWrapper(localName = "GetMessagesResponse", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", className = "uk.co.somestuff.dave.walldisplaycontroller._22_01_2022.GetMessagesResponse")
    @WebResult(name = "GetMessagesResult", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022")
    public uk.co.somestuff.dave.walldisplaycontroller._22_01_2022.ArrayOfMessage getMessages(

        @WebParam(name = "TokenHeader", targetNamespace = "http://dave.somestuff.co.uk/WallDisplayController/22-01-2022", header = true)
        TokenHeader tokenHeader
    );
}
